# Generated by Django 4.2 on 2024-09-17 03:40

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_uploadavatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='uploadavatar',
            name='avatar',
            field=models.ImageField(upload_to=mainapp.models.upload_file_path),
        ),
    ]
