# Generated by Django 4.2 on 2024-09-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_tag_remove_article_tags_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
